# Docker Compose configuration for Google Task Calendar Remote MCP Server
# For local development and production deployment

version: '3.8'

services:
  google-task-calendar-remote:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: google-task-calendar-remote
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      # Server Configuration (non-sensitive)
      - NODE_ENV=production
      - PORT=3001
      - LOG_LEVEL=debug
    volumes:
      # Optional: Mount logs directory
      - ./logs:/app/logs
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

# For Synology NAS deployment, you can also add:
# volumes:
#   google_credentials:
#     driver: local